### ISSUE TITLE
helm-core does not provide helm now

### ISSUE THREAD

**Issue by jian-lin** [emacs-jp/helm-migemo#8]
What about replacing `(require 'helm)` with `(require 'helm-core)`?

ref: https://github.com/NixOS/nixpkgs/issues/335442

**Comment by syohex** [comment]
I fixed it #9. BTW this package is no longer necessary because helm provides `helm-migemo-mode` now and we should use it instead of this package

**Comment by jian-lin** [comment]
Thanks.

> this package is no longer necessary because helm provides `helm-migemo-mode` now and we should use it instead of this package

I am not a user of both these packages.  I find this error in our NixOS CI which builds all packages in MELPA and (non)GNU(devel) ELPA.

If `helm-migemo-mode` is preferred, maybe this package should be removed from MELPA.
